### ISSUE TITLE
Version 2 roadmap

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/kanbasu#41]
- [x] Clean-up all code flagged as deprecated until now
- [x] Use classes instead of styling default form elements (`input[type='text'], input[type='search'], …`)
- [x] Use Flexbox for media object
- [x] Use Flexbox for Grid by default, drop inline-block version
- [x] Use Flexbox for list-inline
- [x] Drop mosaic component in favor of grid/media
- [x] Don’t make dl--inline depends on the presence of the float helper partial
- [x] Reduce madness of padding calculation for buttons and form fields
- [x] Update Normalize
- [x] Bump browsers support to IE11 / Flexbox required
- [x] Add a customizable container/wrapper element #46 
- [x] Drop absolute positioning classes?
- [x] Write migration guide
- [x] Create a responsive table component #14
- [x] Keep version 1 documentation somewhere and link it from the new documentation
